### PR TITLE
chore: add a Github issue template for feature requests

### PR DESCRIPTION
**Pull request by sdenef-adeo**

### CODE REVIEW

**Review by BrunoReboul — CHANGES_REQUESTED** [review]
Thanks, this was missing.
Would you add a bug report template too please?

**Comment by sdenef-adeo** [comment]
> Thanks, this was missing.
> Would you add a bug report template too please?

It should be good.

**Comment by BrunoReboul** [comment]
Thks

**Review by BrunoReboul — APPROVED** [review]
Thks

**Pull request merged**
